#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0xA8974FD444F9305C (vhaisman@gmail.com)
#
Name     : log4cplus
Version  : 1.2.1
Release  : 1
URL      : https://github.com/log4cplus/log4cplus/releases/download/REL_1_2_1/log4cplus-1.2.1.tar.gz
Source0  : https://github.com/log4cplus/log4cplus/releases/download/REL_1_2_1/log4cplus-1.2.1.tar.gz
Source1  : https://github.com/log4cplus/log4cplus/releases/download/REL_1_2_1/log4cplus-1.2.1.tar.gz.sig
Summary  : log4cplus, C++ logging library
Group    : Development/Tools
License  : Apache-2.0
Requires: log4cplus-lib = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : grep
BuildRequires : pkgconfig(Qt5Core)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
log4cplus is a simple to use C++ logging API providing thread-safe, 
flexible, and arbitrarily granular control over log management and 
configuration. It is modeled after the Java log4j API.

%package dev
Summary: dev components for the log4cplus package.
Group: Development
Requires: log4cplus-lib = %{version}-%{release}
Provides: log4cplus-devel = %{version}-%{release}
Requires: log4cplus = %{version}-%{release}

%description dev
dev components for the log4cplus package.


%package lib
Summary: lib components for the log4cplus package.
Group: Libraries

%description lib
lib components for the log4cplus package.


%prep
%setup -q -n log4cplus
cd %{_builddir}/log4cplus

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703092321
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1703092321
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/log4cplus/appender.h
/usr/include/log4cplus/asyncappender.h
/usr/include/log4cplus/boost/deviceappender.hxx
/usr/include/log4cplus/clogger.h
/usr/include/log4cplus/config.hxx
/usr/include/log4cplus/config/defines.hxx
/usr/include/log4cplus/config/macosx.h
/usr/include/log4cplus/config/win32.h
/usr/include/log4cplus/config/windowsh-inc.h
/usr/include/log4cplus/configurator.h
/usr/include/log4cplus/consoleappender.h
/usr/include/log4cplus/fileappender.h
/usr/include/log4cplus/fstreams.h
/usr/include/log4cplus/helpers/appenderattachableimpl.h
/usr/include/log4cplus/helpers/connectorthread.h
/usr/include/log4cplus/helpers/fileinfo.h
/usr/include/log4cplus/helpers/lockfile.h
/usr/include/log4cplus/helpers/loglog.h
/usr/include/log4cplus/helpers/logloguser.h
/usr/include/log4cplus/helpers/pointer.h
/usr/include/log4cplus/helpers/property.h
/usr/include/log4cplus/helpers/queue.h
/usr/include/log4cplus/helpers/sleep.h
/usr/include/log4cplus/helpers/snprintf.h
/usr/include/log4cplus/helpers/socket.h
/usr/include/log4cplus/helpers/socketbuffer.h
/usr/include/log4cplus/helpers/stringhelper.h
/usr/include/log4cplus/helpers/thread-config.h
/usr/include/log4cplus/helpers/timehelper.h
/usr/include/log4cplus/hierarchy.h
/usr/include/log4cplus/hierarchylocker.h
/usr/include/log4cplus/internal/cygwin-win32.h
/usr/include/log4cplus/internal/env.h
/usr/include/log4cplus/internal/internal.h
/usr/include/log4cplus/internal/socket.h
/usr/include/log4cplus/layout.h
/usr/include/log4cplus/log4judpappender.h
/usr/include/log4cplus/logger.h
/usr/include/log4cplus/loggingmacros.h
/usr/include/log4cplus/loglevel.h
/usr/include/log4cplus/mdc.h
/usr/include/log4cplus/ndc.h
/usr/include/log4cplus/nteventlogappender.h
/usr/include/log4cplus/nullappender.h
/usr/include/log4cplus/qt4debugappender.h
/usr/include/log4cplus/socketappender.h
/usr/include/log4cplus/spi/appenderattachable.h
/usr/include/log4cplus/spi/factory.h
/usr/include/log4cplus/spi/filter.h
/usr/include/log4cplus/spi/loggerfactory.h
/usr/include/log4cplus/spi/loggerimpl.h
/usr/include/log4cplus/spi/loggingevent.h
/usr/include/log4cplus/spi/objectregistry.h
/usr/include/log4cplus/spi/rootlogger.h
/usr/include/log4cplus/streams.h
/usr/include/log4cplus/syslogappender.h
/usr/include/log4cplus/tchar.h
/usr/include/log4cplus/thread/impl/syncprims-cxx11.h
/usr/include/log4cplus/thread/impl/syncprims-impl.h
/usr/include/log4cplus/thread/impl/syncprims-pthreads.h
/usr/include/log4cplus/thread/impl/syncprims-win32.h
/usr/include/log4cplus/thread/impl/threads-impl.h
/usr/include/log4cplus/thread/impl/tls.h
/usr/include/log4cplus/thread/syncprims-pub-impl.h
/usr/include/log4cplus/thread/syncprims.h
/usr/include/log4cplus/thread/threads.h
/usr/include/log4cplus/tracelogger.h
/usr/include/log4cplus/tstring.h
/usr/include/log4cplus/version.h
/usr/include/log4cplus/win32consoleappender.h
/usr/include/log4cplus/win32debugappender.h
/usr/lib64/liblog4cplus.so
/usr/lib64/pkgconfig/log4cplus.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblog4cplus-1.2.so.5
/usr/lib64/liblog4cplus-1.2.so.5.1.6
